name: Deployment aws-demo-attack-lab-v2

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  destroy_deployment:
    permissions:
      contents: read
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    runs-on: ubuntu-24.04
    name: Terraform Deployment
    env:
      working-directory: ./infra
      AWS_REGION: ${{ vars.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      S3_BACKEND: ${{ vars.S3_BACKEND }}
      DEPLOYMENT_NAME: ${{ vars.DEPLOYMENT_NAME }}
    outputs:
      KUBE_CONFIG: ${{ steps.step4.outputs.KUBE_CONFIG }}
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - name: Terraform Deployment
        id: init
        working-directory: ${{ env.working-directory }}
        run: |
          terraform init -backend-config="bucket=${{ env.S3_BACKEND }}" -backend-config="region=${{ env.AWS_REGION }}" -backend-config="key=terraform.tfstate"
          terraform destroy --auto-approve
